### ISSUE TITLE
Open Authentication Not Working

### ISSUE THREAD

**Issue by dlevinson5** [wunderlist/api#9] opened 2015-10-22 04:21 UTC
Until a few days ago I could provide a port number as part of the redirect_ui parameter. As of today this i not working. I have a local desktop application that depends on being able to redirect the authentication back to http://loalhost:8094/oauth.

This was again working until recently and it appears that your server side redirect is removing the port information from the redirect. 

How can I get back this functionality?

**Comment by duncan** [comment] 2015-10-22 07:01
Thanks for the report. That's definitely a bug that we'll look into.

**Comment by idpaterson** [comment] 2015-10-23 12:35
I have received several bug reports for this problem which is affecting my application as well [as noted here](https://github.com/idpaterson/alfred-wunderlist-workflow/issues/82). Thanks for looking into it.

**Comment by rotev** [comment] 2015-10-26 11:17
I confirm that this issue was caused by a recent change to our API, and I'm currently working to fix it.

**Comment by rotev** [comment] 2015-10-26 15:45
@dlevinson5, @idpaterson, this bug is fixed now!

**Closed by rotev** 2015-10-26 15:45 UTC
Labels: bug

**Comment by idpaterson** [comment] 2015-10-26 16:07
@rotem, thank you! I can confirm the fix, this looks good on my end.
